### ISSUE TITLE
STA9750 Whaleron MiniProject #00

### ISSUE THREAD

**Issue by whaleron** [whaleron/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://whaleron.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @whaleron !

Peer Feedback:

- @haolinnn
- @SethKauf
- @cndy17

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @whaleron.

Website URL should be: https://whaleron.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @whaleron and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by whaleron** [comment]
@cndy17 I know you posted in a separate thread, but I wanted to make sure that it will be visible to everyone; I think your comment should be in this thread.  https://github.com/whaleron/STA9750-2024-FALL/issues/2#issuecomment-2347354835

**Comment by cndy17** [comment]
Ohh I see! Thanks for pointing that out. 
Hi Valeriia! I really like the use of Markdown to include links to X, Twitter, and the added bonus of your ML projects! You have some interesting projects there. It could be nice to have those listed on the GitHub site as well in a bulleted list. This GitHub site is also a great example of how to add your own photo with Markdown as well.

**Comment by SethKauf** [comment]
Hi @whaleron, I think this is really cool and your ML Projects look awesome.

Would your headshot be better if centered?

**Comment by haolinnn** [comment]
Hi @whaleron, I like your whole layout and theme. Also, I like the idea of putting your photo and links on the page.
