### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by cndy17** [whaleron/STA9750-2024-FALL#2]
Hi Valeriia! I really like the use of Markdown to include links to X, Twitter, and the added bonus of your ML projects! You have some interesting projects there. It could be nice to have those listed on the GitHub site as well in a bulleted list. This GitHub site is also a great example of how to add your own photo with Markdown as well.

**Comment by whaleron** [comment]
@cndy17 Thank you! Good point, but those in Python so want to keep them separate 😮‍💨
