### ISSUE TITLE
STA9750 whaleron MiniProject #01

### ISSUE THREAD

**Issue by whaleron** [whaleron/STA9750-2024-FALL#3]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!
https://whaleron.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @whaleron !

Peer Feedback:

- @YantingZhao11
- @chrismontano129
- @Dani-0000
- @Cdiallo77

It is now time for the peer feedback round for Mini-Project #01. Please
review @whaleron's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @whaleron, but you are of course
welcome to initiate a discussion.

@whaleron: please engage fully with your peers. They are here to help you!

Submission URL should be: https://whaleron.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by Dani-0000** [comment]
Hi @whaleron 

I enjoyed the links you added to your project, they are very cool. Written Communication was a 10, I liked that you included an introduction and broke down each part for the reader. Project Skeleton is a 10, you followed the instructions and answered all the questions. Formatting & Display 10, I like how you formatted your question and then had the code under. Code Quality 10, your code was able to display the graphs and ran smoothly. 
Total score 53/50 -extra three points for the links. Great Job!

**Comment by YantingZhao11** [comment]
Hi @whaleron,

Please see feedback below:

Written Communication: 7.5/10
The report is clear, but could flow better between sections. More explanation on how findings relate to one another ould improve the flow.

Project Skeleton: 9.5/10
Well-organized and covers all tasks. A bit more detail in some areas would enhance structure.

Formatting & Display: 9/10
The layout is clean, but incorporating more visuals like charts would make it more engaging.

Code Quality: 10/10

Data Preparation: 10/10

Best,
Yanting

**Comment by Cdiallo77** [comment]
Hi @whaleron,
The work you did looks great to me, since you were able to answer all the questions. I wish you had answered the last part showing the code you used. Other than that, I give you:

- Written communication:  9.5/10 
- Project Skeleton 10/10
- Formatting: 10/10 - You can always improve, but since it is the 1st project, I think you did great. 
- Code quality 10/10 They all run and you were able to display the answers. 
- Data prep: 10/10 

Well done, keep up with the good work.
Cdiallo77

**Comment by charles-ramirez** [comment]
Hi, @Chrismontano129, 

This is just a reminder that your peer review is due today at 11:45pm.

**Comment by Chrismontano129** [comment]
Hi @whaleron 

-Written Communication (10)
Clear and outlines the anaylsis in a structured way.

-Project Skeleton (10)
The project includes all necessary operations, such as downloading, cleaning, combining, and analyzing data. The problem definition is strictly followed and the implementation is comprehensive.

-Formatting & Display (10)
 Tables and data summaries are generally well-presented

-Code Quality (10)
The code is well-commented, with straightforward instructions and clear variable names. 

-Data Preparation(10)
